### ISSUE TITLE
Multiple observed values for the same sampling date/treatment in strawberries

### ISSUE THREAD

**Issue by lpmorenoc** [DSSAT/dssat-csm-data#102]
Some of the experiments of strawberries have multiple observed values for the same sampling date/treatment in strawberries. It is better to register the mean value per date/treatment. @alwinhopf could you check this?
<img width="756" alt="image" src="https://github.com/DSSAT/dssat-csm-data/assets/6476135/2dd3ffc8-09bd-4846-880f-7decdc011333">

**Comment by alwinhopf** [comment]
Yes these are observations for repeated samples for the same date/treatment. I was recommended to better keep these this way instead of 1) only providing a mean value (and losing individual observations) or 2) splitting repetitions into individual treatments (requiring additional "fake" treatments in the X file). Happy to change it though if there is a consensus 
@GerritHoogenboom

**Comment by chporter** [comment]
FileT can have multiple entries for the same date. FileA must be the average.
